#!/usr/bin/env bash

# Fail on errors
set -e

# Run behat commands in a running behat container
docker exec $(docker-compose ps -q behat) behat --colors --format=pretty --out=std --format=html --out=html_report "$@"
